package com.hardy.fleamarket.entity;

public class Password {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.id
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.phone
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column password.password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    public Password(Integer id, Long phone, String password) {
        this.id = id;
        this.phone = phone;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.id
     *
     * @return the value of password.id
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.phone
     *
     * @return the value of password.phone
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column password.password
     *
     * @return the value of password.password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    public String getPassword() {
        return password;
    }
}