package com.hardy.fleamarket.dao;

import com.hardy.fleamarket.entity.Password;

public interface PasswordMapper {

    Password selectByPhone(Long phone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    int insert(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    int insertSelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    Password selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    int updateByPrimaryKeySelective(Password record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table password
     *
     * @mbg.generated Sun Dec 29 17:59:01 CST 2019
     */
    int updateByPrimaryKey(Password record);
}